package com.clinic.entity;

import java.util.Date;

// Generated Sep 5, 2020 3:52:44 PM by Hibernate Tools 4.3.1

/**
 * PatientVisit generated by hbm2java
 */
public class PatientVisit implements java.io.Serializable {

	private PatientVisitId id;
//	private ClinicPatient clinicPatient;
	private String visitDt;
	private String patientDiagnose;
	private Date visitUtilDt;

	public PatientVisit() {
	}

	public PatientVisit(PatientVisitId id) {
		this.id = id;
	}

	public PatientVisit(PatientVisit patientVisit) {
		this.id = new PatientVisitId(patientVisit.getId());
//		this.clinicPatient = patientVisit.getClinicPatient();
		this.visitDt = patientVisit.getVisitDt();
		this.patientDiagnose = patientVisit.getPatientDiagnose();
	}

	public PatientVisit(PatientVisitId id, ClinicPatient clinicPatient, String visitDt) {
		this.id = id;
//		this.clinicPatient = clinicPatient;
		this.visitDt = visitDt;
	}

	public PatientVisit(PatientVisitId id, ClinicPatient clinicPatient, String visitDt, String patientDiagnose) {
		this.id = id;
//		this.clinicPatient = clinicPatient;
		this.visitDt = visitDt;
		this.patientDiagnose = patientDiagnose;
	}

	public PatientVisitId getId() {
		return this.id;
	}

	public void setId(PatientVisitId id) {
		this.id = id;
	}

	/*public ClinicPatient getClinicPatient() {
		return this.clinicPatient;
	}

	public void setClinicPatient(ClinicPatient clinicPatient) {
		this.clinicPatient = clinicPatient;
	}*/

	public String getVisitDt() {
		return this.visitDt;
	}

	public void setVisitDt(String visitDt) {
		this.visitDt = visitDt;
	}

	public String getPatientDiagnose() {
		return this.patientDiagnose;
	}

	public void setPatientDiagnose(String patientDiagnose) {
		this.patientDiagnose = patientDiagnose;
	}

	public Date getVisitUtilDt() {
		return visitUtilDt;
	}

	public void setVisitUtilDt(Date visitUtilDt) {
		this.visitUtilDt = visitUtilDt;
	}

}
